# Generated by Django 2.2.5 on 2019-09-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('car_brand', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('style', models.CharField(max_length=10)),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=True, to='car.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('style_id', models.OneToOneField(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='car.Style')),
                ('seat', models.IntegerField()),
                ('door', models.IntegerField()),
                ('gear_box', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
                ('drive', models.CharField(max_length=255)),
                ('skylight', models.CharField(max_length=255)),
                ('tank', models.CharField(max_length=255)),
                ('radar', models.CharField(max_length=255)),
                ('gear', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('sup_img', models.CharField(max_length=255)),
                ('style_id', models.ForeignKey(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
            ],
        ),
        migrations.CreateModel(
            name='MainImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('main_img', models.CharField(max_length=255)),
                ('style_id', models.OneToOneField(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('deposit', models.IntegerField()),
                ('style_id', models.OneToOneField(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
            ],
        ),
        migrations.CreateModel(
            name='DayRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('daily_rental', models.IntegerField()),
                ('style_id', models.OneToOneField(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
            ],
        ),
        migrations.CreateModel(
            name='DayInsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('daily_insurance', models.IntegerField()),
                ('style_id', models.OneToOneField(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
            ],
        ),
    ]
