# Generated by Django 2.2.5 on 2019-10-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClassification',
            fields=[
                ('car_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('car_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('type_id', models.ForeignKey(db_column='car_type_id', on_delete=django.db.models.deletion.CASCADE, to='car.TypeClassification')),
            ],
        ),
    ]
