# Generated by Django 2.2.5 on 2019-10-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_type_typeclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='style_id',
            field=models.ForeignKey(db_column='style_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='car.Style'),
            preserve_default=False,
        ),
    ]
