# Generated by Django 2.2.5 on 2019-09-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='car',
            new_name='car_style',
        ),
    ]
