# Generated by Django 2.2.5 on 2019-09-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
                ('store_tel', models.CharField(max_length=255)),
                ('store_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='store_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField()),
                ('car_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Style')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.store')),
            ],
        ),
    ]
