# Generated by Django 2.2.5 on 2019-09-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_identification_identification_type'),
        ('order', '0003_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('identification_num', models.CharField(max_length=255)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.identification_type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.userorder')),
            ],
        ),
    ]
